export const FOODS = [
{n:"Jordbær, rå",c:38},
{n:"Æble, uspec., råt",c:55},
{n:"Banan, rå",c:93},
{n:"Kartoffel, uspec., rå",c:77},
{n:"Sødmælk, konventionel (ikke-økologisk)",c:63},
{n:"Persille, rå",c:48},
{n:"Pære, rå",c:49},
{n:"Rabarber, rå",c:26},
{n:"Solbær, rå",c:75},
{n:"Yoghurt naturel, sødmælk",c:62},
{n:"Bladselleri, rå",c:23},
{n:"Blomkål, uspecificeret, rå",c:28},
{n:"Broccoli, rå",c:35},
{n:"Voksbønner, rå",c:35},
{n:"Citron, rå",c:44},
{n:"Dild, rå",c:48},
{n:"Grønkål, rå",c:60},
{n:"Gulerod, uspec., rå",c:36},
{n:"Hornfisk, rå",c:107},
{n:"Hvidkål, rå",c:32},
{n:"Hyben, rå",c:79},
{n:"Hyldebær, rå",c:67},
{n:"Laks, atlantisk, vild, rå",c:159},
{n:"Majskolbe, rå",c:91},
{n:"Kærnemælk",c:36},
{n:"Letmælk, konventionel (ikke-økologisk)",c:48},
{n:"Makrel, rå",c:187},
{n:"Mandel, rå",c:606},
{n:"Vandmelon, rå",c:33},
{n:"Peberfrugt, grøn, rå",c:22},
{n:"Peberfrugt, rød, rå",c:31},
{n:"Radise, rå",c:12},
{n:"Ribs, rå",c:63},
{n:"Rosenkål, uspec., rå",c:53},
{n:"Rødbede, rå",c:52},
{n:"Rødkål, rå",c:32},
{n:"Rødspætte, rå",c:85},
{n:"Selleri, rod, rå",c:34},
{n:"Sild, marineret",c:272},
{n:"Sild, rå",c:190},
{n:"Spidskål, rå",c:27},
{n:"Spinat, rå",c:24},
{n:"Stikkelsbær, rå",c:44},
{n:"Tomat, uspec., rå",c:21},
{n:"Vindrue, rå",c:67},
{n:"Grønne ærter, rå",c:70},
{n:"Squash, rå",c:15},
{n:"Artiskok, rå",c:46},
{n:"Mungbønner, tørrede, rå",c:324},
{n:"Havregryn, uspec.",c:366},
{n:"Rugmel, groft, fuldkornsrugmel",c:333},
{n:"Grahamsmel, fuldkornshvedemel",c:331},
{n:"Ingefær, rod, rå",c:49},
{n:"Okra, rå",c:29},
{n:"Asparges, grønne, rå",c:26},
{n:"Fennikel, knold, rå",c:23},
{n:"Mørksej, rå",c:79},
{n:"Boghvede, hel, rå",c:341},
{n:"Aubergine, rå",c:17},
{n:"Appelsin, rå",c:49},
{n:"Lammekød, kølle, uspec., rå",c:180},
{n:"Torsk, filet, rå",c:75},
{n:"Feta, 40+",c:258},
{n:"Grisekød, nakkekam med svær, rå",c:275},
{n:"Risengryn, grødris, brune, rå",c:362},
{n:"Sukker, stødt melis (sakkarose)",c:400},
{n:"Grisefedt, afsmeltet, Raffinol",c:891},
{n:"Grisefedt, afsmeltet",c:891},
{n:"Mineralvand, dansk vand o.lign.",c:0},
{n:"Fiskeolie, hydrogeneret",c:899},
{n:"Gås, kød og skind, rå",c:366},
{n:"Kokosnød, rå",c:385},
{n:"Snacks, ekspanderet, kartoffelbasis",c:490},
{n:"Salat, mayonnaise-, makrel-",c:398},
{n:"Soja sauce",c:56},
{n:"Ost, fast, 40+, alle typer",c:312},
{n:"Ylette naturel",c:58},
{n:"Mozzarella, 45+",c:326},
{n:"Smelteost, 45+",c:307},
{n:"And, kød og skind, rå",c:400},
{n:"Sigtemel",c:350},
{n:"Buddingpulver",c:348},
{n:"Havarti, 30+",c:291},
{n:"Danbo, 45+",c:325},
{n:"Rullepølse, lammekød, pålæg",c:362},
{n:"Løg, ristede",c:574},
{n:"Te, drikkeklar, uspec.",c:0},
{n:"Kastanje, ægte, rå",c:189},
{n:"Kaffe, instant, drikkeklar",c:3},
{n:"Esrom, 45+",c:331},
{n:"Elbo, 40+",c:321},
{n:"Kartoffelchips, grove",c:498},
{n:"Roquefort, 50+",c:343},
{n:"Kaffe, instant, decaffeinated, drikkeklar",c:4},
{n:"Danablu 50+",c:350},
{n:"Brie, 60+",c:342},
{n:"Bacon, kogestykke, rå",c:379},
{n:"Kaffe, drikkeklar",c:1},
{n:"Rugkerner, hele/knækkede",c:332},
{n:"Leverpølse, pålæg",c:393},
{n:"Creme fraiche 50 %",c:466},
{n:"Ost, fast, 45+, alle typer",c:335},
{n:"Hørfrø, rå",c:464},
{n:"Jordnød, tørret",c:596},
{n:"Fløde 50 %",c:468},
{n:"Peber, hvid",c:307},
{n:"Sojamel",c:449},
{n:"Ris, brune, rå",c:358},
{n:"Skummetmælkspulver",c:356},
{n:"Havarti, 45+",c:343},
{n:"Hyben pulver, tørret",c:278},
{n:"Østers, rå",c:61},
{n:"Hvidvin, tør",c:68},
{n:"Fiskeboller, konserves",c:68},
{n:"Rugbrød, revet, med brunt sukker, uspec.",c:348},
{n:"Hvidvin, uspec.",c:83},
{n:"Hvidvin, Rhinskvin",c:67},
{n:"Tomat, soltørret",c:282},
{n:"Ymer naturel",c:72},
{n:"Rødvin, rosévin, uden alkohol",c:15},
{n:"Hvidvin, medium",c:79},
{n:"Småkage, finsk brød",c:537},
{n:"Hvidvin, uden alkohol",c:19},
{n:"Byggryn, rå",c:349},
{n:"Risstivelse",c:343},
{n:"Lakridskonfekt",c:395},
{n:"Wienerbrød, spandauer",c:397},
{n:"Dressing, fransk",c:469},
{n:"Danablu 60+",c:407},
{n:"Fynbo, 45+",c:357},
{n:"Æg, høne, æggehvide, pasteuriseret",c:43},
{n:"Stenbider, røget",c:373},
{n:"Hvedekerner, hele/knækkede",c:340},
{n:"Rasp",c:351},
{n:"Æblemost, uspec.",c:48},
{n:"Sagogryn (kartoffelstivelse)",c:354},
{n:"Maribo, 45+",c:361},
{n:"Sennep, brun, færdiglavet",c:146},
{n:"Hvidløg, rå",c:101},
{n:"Rosévin",c:72},
{n:"Millionbøf, uspec.",c:127},
{n:"Samsø, 45+",c:362},
{n:"Spædbørnsmad, modermælkserstatning, lavt jernindhold, pulver",c:519},
{n:"Sherry, medium",c:118},
{n:"Rødvin, uspec.",c:77},
{n:"Cheshire, 50+",c:381},
{n:"Æg, høne, æggehvide, rå",c:44},
{n:"Bacon, stegestykke, rå",c:430},
{n:"Vermouth, tør",c:118},
{n:"Vermouth, sød",c:145},
{n:"Sveske, rå",c:230},
{n:"Tamarind, rå",c:256},
{n:"Croissant",c:420},
{n:"Æg, høne, æggehvide, tørret",c:357},
{n:"Eddike",c:20},
{n:"Madeira",c:166},
{n:"Campari",c:180},
{n:"Tebirkes",c:434},
{n:"Ost, blå- og hvidskimmel, 70+",c:449},
{n:"Hvidvin, sød",c:96},
{n:"Bitter, uspec.",c:211},
{n:"Peber, sort",c:304},
{n:"Bitter, Gammel Dansk Bitter Dram",c:214},
{n:"Cognac",c:224},
{n:"Hvidvin, mousserende, champagne",c:76},
{n:"Svenbo, 45+",c:377},
{n:"Snaps, krydder-, uspec.",c:268},
{n:"Sherry, tør",c:117},
{n:"Oliven, sorte, uden sten, i saltlage",c:171},
{n:"Spirituosa, gennemsnitlige værdier",c:234},
{n:"Vodka",c:234},
{n:"Skærekage, citronkage",c:429},
{n:"Bitter, krabask bitter",c:228},
{n:"Emmentaler, 45+",c:377},
{n:"Morgenmadsprodukt, Rice Krispies",c:372},
{n:"Snaps, 40 % vol., uspec.",c:224},
{n:"Ispind, jordbær",c:157},
{n:"Citronsaft, friskpresset",c:31},
{n:"Esrom, 60+",c:426},
{n:"Flødeyoghurt med frugt, 9 % fedt",c:128},
{n:"Tofu, sojabønneost",c:126},
{n:"Portvin",c:153},
{n:"Skærekage, chokoladekage/-pie",c:432},
{n:"Bouillon, hønsekød, spiseklar",c:4},
{n:"Wienerbrød, kanelsnegl",c:412},
{n:"Wienerbrød, uspec.",c:442},
{n:"Skærekage, formkage, uspec.",c:424},
{n:"Pop corn, traditionelle",c:468},
{n:"Bulgur, parboiled, rå",c:342},
{n:"Linsespirer, rå",c:123},
{n:"Whisky",c:252},
{n:"Spegepølse, oksekød",c:383},
{n:"Havarti, 60+",c:424},
{n:"Syrnet fløde 9 % (Fraiche 9%)",c:118},
{n:"Pølse, tepølse",c:478},
{n:"Hasselnød, tørret",c:657},
{n:"Fløde 9 %",c:111},
{n:"Pasta, rå",c:361},
{n:"Kvark, 5+",c:58},
{n:"Grana, 32+",c:354},
{n:"Parmesan, 32+",c:360},
{n:"Gin",c:265},
{n:"Agurk, syltet, uden tilsat sukker",c:10},
{n:"Bagegær, presset, rå",c:114},
{n:"Småkage, vanillekranse",c:528},
{n:"Cheddar, 50+",c:405},
{n:"Fiskefars, rå",c:108},
{n:"Rom",c:278},
{n:"Pistacienød, tørret",c:606},
{n:"Flødeboller, skumboller",c:406},
{n:"Hirseflager",c:370},
{n:"Rygeost, 1 % fedt",c:68},
{n:"Torsk, lever, konserves",c:532},
{n:"Snacks, ekspanderet, majsbasis",c:503},
{n:"Myseost, 33+",c:433},
{n:"Gruyere, 45+",c:396},
{n:"Rødkål, konserves, uden tilsat sukker",c:20},
{n:"Wienerbrød, kringle/stang",c:416},
{n:"Sherry, sød",c:136},
{n:"Figen, tørret",c:292},
{n:"Tranebær, rå",c:42},
{n:"Tørkage, linse",c:385},
{n:"Pop Corn (poppede majskærner)",c:489},
{n:"Wienerbrød, julekage",c:458},
{n:"Spegepølse",c:455},
{n:"Skærekage, sandkage",c:446},
{n:"Kvæde, rå",c:60},
{n:"Græskar, rå",c:18},
{n:"Dressing, blue cheese",c:520},
{n:"Kinaradise, japanræddike, rå",c:17},
{n:"Sesamfrø, hele",c:605},
{n:"Oliven, grønne, marinerede, konserves",c:134},
{n:"Tang, agar, tørret",c:161},
{n:"Knækbrød, rug-, groft",c:343},
{n:"Makaroni, spaghetti, fuldkorns-, rå",c:352},
{n:"Rugbrød, fuldkorn, importeret",c:200},
{n:"Pære, konserves",c:71},
{n:"Majroe, rå",c:26},
{n:"Bitter, sød, uspec.",c:265},
{n:"Bønnespirer, adzuki, rå",c:131},
{n:"Hirse, hele korn",c:368},
{n:"Pop corn, mikroovn",c:505},
{n:"Musling, rå",c:83},
{n:"Agurk, rå",c:12},
{n:"Loquat, japansk mispel, rå",c:49},
{n:"Cashewnød, olieristet",c:610},
{n:"Wienerbrød, smørkrans",c:469},
{n:"Nøddepasta med cacao, smørepålæg",c:527},
{n:"Cornflakes, uspec.",c:374},
{n:"Müsli, uspec.",c:405},
{n:"Forloren skildpadde, uspec.",c:109},
{n:"Abrikos, konserves, let sukkerlage",c:68},
{n:"Agurk, syltet",c:58},
{n:"Kødpølse, fedtreduceret, pålæg",c:130},
{n:"Druesaft",c:63},
{n:"Krebs, rå",c:68},
{n:"Majsstivelse",c:361},
{n:"Gulerod, konserves",c:23},
{n:"Kartoffelmos, pulver med tørmælk",c:333},
{n:"Rugbrød, lyst",c:205},
{n:"Bitter, jägermeister",c:294},
{n:"Salt, bordsalt (jodberiget)",c:0},
{n:"Pumpernikkel",c:196},
{n:"Forårsrulle, dybfrost",c:151},
{n:"Abrikos, konserves, uden tilsat sukker",c:27},
{n:"Græskar, konserves",c:103},
{n:"Ananas, konserves",c:64},
{n:"Løg, hakkede, dybfrost",c:28},
{n:"Flødeskumskage, lagkagesnitte",c:302},
{n:"Krydder",c:385},
{n:"Tvebakker",c:375},
{n:"Cayote, Kayote, rå",c:19},
{n:"Knækbrød, rug-, fint",c:345},
{n:"Sennep, gul, færdiglavet",c:165},
{n:"Fersken, konserves",c:71},
{n:"Likør, uspec.",c:269},
{n:"Cornflakes, frosted",c:381},
{n:"Solsikkefrø, afskallede, tørrede",c:620},
{n:"Sauce, gravad laks",c:563},
{n:"Snacks, ekstruderet, majsbasis",c:537},
{n:"Havregryn, beriget",c:362},
{n:"Netmelon, rå",c:23},
{n:"Tomat, dansk, rå",c:20},
{n:"Mandarin, konserves",c:62},
{n:"Rødspætte, filet, paneret, dybfrost",c:136},
{n:"Abrikos, tørret",c:248},
{n:"Sauce, barbeque",c:147},
{n:"Müsli med tilsat sukker.",c:370},
{n:"Müsli uden tilsat sukker.",c:367},
{n:"Bondebrød, industrifremstillet",c:225},
{n:"Lime, rå",c:37},
{n:"Paradisæble, rå",c:83},
{n:"Hyldebærsaft, sur, koncentreret",c:31},
{n:"Fløde 13 % (UHT)",c:147},
{n:"Frølår, dybfrost",c:69},
{n:"Peber, chili, konserves",c:26},
{n:"Sesamfrø, afskallede",c:643},
{n:"Jordbærsaft, sur, koncentreret",c:35},
{n:"Hindbærsaft, sur, koncentreret",c:35},
{n:"Knude, rå",c:70},
{n:"Kulmule, rå",c:69},
{n:"Flødeskumskage, jordbærkage",c:216},
{n:"Dressing, mayonnaise, kalorielet",c:179},
{n:"Likør, Curacao",c:297},
{n:"Salat, Iceberg, rå",c:16},
{n:"Havregryn, ikke beriget",c:366},
{n:"Ribssaft, sur, koncentreret",c:39},
{n:"Jordbær, dybfrost, sukrede",c:84},
{n:"Fløde 13 %",c:151},
{n:"Sakkarin",c:360},
{n:"Salami",c:509},
{n:"Ræddike, rå",c:22},
{n:"Cantaloupe (melon), rå",c:36},
{n:"Rødbede, konserves, uden tilsat sukker",c:29},
{n:"Kødboller, konserves",c:126},
{n:"Blæksprutte, rå",c:77},
{n:"Peberrod, rå",c:104},
{n:"Jordbær i sukkerlage, konserves",c:81},
{n:"Grisekød i karrysovs, dybfrost",c:119},
{n:"Solbærsaft, sur, koncentreret",c:51},
{n:"Vinbjergssnegle, rå",c:84},
{n:"Gulerod, dybfrost",c:30},
{n:"Peberfrugt, konserves",c:19},
{n:"Tørkage, kokosmakroner",c:453},
{n:"Ispind, vanille",c:186},
{n:"Vindrue, grønne, rå",c:69},
{n:"Papaya, rå",c:47},
{n:"Sødmælkspulver",c:493},
{n:"Pizza romana, dybfrost",c:177},
{n:"Kirsebærsaft, sur, koncentreret",c:59},
{n:"Tyttebær, syltede",c:156},
{n:"Pecannød, tørret",c:721},
{n:"Hytteost, 20+",c:99},
{n:"Reje, dybvands-, kogt, dybfrost",c:68},
{n:"Kålrabi (kålroe), rå",c:34},
{n:"Frugtkvark",c:166},
{n:"Torsk, rogn, konserves",c:99},
{n:"Valle",c:27},
{n:"Reje, dybvands-, konserves",c:79},
{n:"Hybensaft, sød, koncentreret",c:231},
{n:"Daddel, tørret",c:309},
{n:"Bouillon, oksekød, terning, spiseklar",c:7},
{n:"Is, tre-farvet",c:198},
{n:"Te, blade",c:233},
{n:"Rabarber, dybfrost",c:26},
{n:"Drueagurk (sylteagurk), rå",c:17},
{n:"Rødtunge, rå",c:72},
{n:"Asier, syltede",c:76},
{n:"Julesalat, rå",c:19},
{n:"Ising, rå",c:75},
{n:"Nyre, kalv, rå",c:95},
{n:"Torsk, filet, paneret, rå",c:113},
{n:"Sortmund, blåhvilling, filet, rå",c:77},
{n:"Lever, gris, i flødesovs, dybfrost",c:124},
{n:"Tørkage, uspec.",c:471},
{n:"Hvilling, rå",c:78},
{n:"Salt, havsalt (ikke jodberiget)",c:0},
{n:"Havreklid, dansk",c:367},
{n:"Gulerod, dansk, rå",c:29},
{n:"Mandarin, rå",c:47},
{n:"Aborre, rå",c:77},
{n:"Torsk, filet, kogt",c:75},
{n:"Havkat, rå",c:97},
{n:"Hjerte, kalv, råt",c:106},
{n:"Nyre, okse, rå",c:106},
{n:"Brosme, rå",c:79},
{n:"Torsk, filet, røget, med skind",c:79},
{n:"Kaktusfigen, rå",c:39},
{n:"Kinakål, rå",c:17},
{n:"Nyre, gris, rå",c:98},
{n:"Sperling, kød, rå",c:79},
{n:"Tørkage, mazariner",c:477},
{n:"Figen, rå",c:77},
{n:"Stjernefrugt, rå",c:33},
{n:"Pighvarre, rå",c:90},
{n:"Kuller, rå",c:77},
{n:"Leverpostej, fedtreduceret",c:150},
{n:"Skrubbe, rå",c:86},
{n:"Salat, endivie, bredbladet (escarole), rå",c:14},
{n:"Lyssej, rå",c:71},
{n:"Skærekage, mazarinkage",c:430},
{n:"Kaviar, uægte (stenbiderrogn)",c:106},
{n:"Pizza napolitana, dybfrost",c:181},
{n:"Salat, egeløv, rå",c:15},
{n:"Gule ærter (flækærter), rå",c:347},
{n:"Kakifrugt (Sharon), rå",c:87},
{n:"Lange, filet, rå",c:80},
{n:"Søtunge, rå",c:85},
{n:"Tomat, flået, konserves",c:21},
{n:"Kødboller, uspec.",c:145},
{n:"Fiskefrikadelle",c:153},
{n:"Salat, endivie, kruset (frisee), rå",c:18},
{n:"Salat, Romaine, romersk, rå",c:17},
{n:"Sandart, rå",c:87},
{n:"Kartoffelmos, pulver uden tørmælk",c:350},
{n:"Rødfisk, rå",c:84},
{n:"Forårsrulle med hakket oksekød og hvidkål, friturestegt, fastfood",c:203},
{n:"Gulerod, importeret, rå",c:33},
{n:"Torsk, lever, røget",c:624},
{n:"Torsk, lever, rå",c:624},
{n:"Nektarin, rå",c:42},
{n:"Gedde, rå",c:90},
{n:"Dressing, olie-eddike, kalorielet",c:49},
{n:"Squash, alle typer, rå",c:17},
{n:"Hvedebrød, groft, kærnebrød",c:231},
{n:"Avocado, rå",c:155},
{n:"Hvedeklid",c:291},
{n:"Rødbede, konserves",c:60},
{n:"Brune linser, tørrede, rå",c:336},
{n:"Tomat, importeret, rå",c:33},
{n:"Hummer, kogt",c:90},
{n:"Hummer, konserves",c:90},
{n:"Salat, hovedsalat, rå",c:14},
{n:"Margarine, 70 %, bordbrug, blød, vegetabilsk fedt",c:681},
{n:"Rødkål, konserves",c:75},
{n:"Litchi, rå",c:71},
{n:"Pizza, dybfrost, uspec.",c:190},
{n:"Granatæble, rå",c:67},
{n:"Guavabær, rå",c:42},
{n:"Havkat, plettet, rå",c:107},
{n:"Musling, konserves",c:103},
{n:"Ananaskirsebær, rå",c:51},
{n:"Rygeost, 10 % fedt",c:130},
{n:"Brasen, rå",c:108},
{n:"Hjerte, okse, råt",c:103},
{n:"Pak choi (bok choy), rå",c:15},
{n:"Hjerte, gris, råt",c:102},
{n:"Rugbrød med fedtrige frø og kerner, industrifremstillet",c:215},
{n:"Valnød, tørret",c:693},
{n:"Asparges, konserves",c:16},
{n:"Hvidløg, tørret, pulver",c:345},
{n:"Pizza med broccoli, dybfrost",c:194},
{n:"Salat, Radicchio rosso, rå",c:24},
{n:"Æg, høne, tørret",c:564},
{n:"Hummer, rå",c:93},
{n:"Jomfruhummer, rå",c:93},
{n:"Knækbrød, hvede-, grahamstype",c:371},
{n:"Karry, pulver",c:303},
{n:"Rødfisk, lille, filet, rå",c:90},
{n:"Kartoffel, chips, fedtreducerede",c:488},
{n:"Tungepølse, pålæg",c:148},
{n:"Sej, filet, dybfrost",c:91},
{n:"Fløde 18 %",c:190},
{n:"Voksbønner, konserves",c:26},
{n:"Hvedebrød, groft, fiberbrød",c:216},
{n:"Skinke, kogt, konserves",c:111},
{n:"Surbrød",c:249},
{n:"Æg, høne, langæg, kogt, dybfrost",c:129},
{n:"Brombær, syltede",c:197},
{n:"Mangomarmelade",c:216},
{n:"Creme fraiche 18 %",c:192},
{n:"Grahamsbrød",c:249},
{n:"Lever, gåse, rå",c:129},
{n:"Salt kød, pålæg",c:100},
{n:"Chokolade, fløde",c:545},
{n:"Sigtebrød",c:249},
{n:"Hvedebrød, italiensk, store, industrifremstillet",c:258},
{n:"Miso, sojapasta",c:167},
{n:"Grønne bønner, konserves",c:25},
{n:"Linser, tørrede, rå",c:347},
{n:"Kråse, kylling, rå",c:113},
{n:"Knudekål, glaskål, rå",c:25},
{n:"Brøndkarse, rå",c:19},
{n:"Dressing, creme fraiche, kalorielet",c:213},
{n:"Æg, høne, blomme, tørret",c:656},
{n:"Flûte, fint, industrifremstillet",c:256},
{n:"Kartoffel, konserves",c:56},
{n:"Paranød, tørret, rå",c:681},
{n:"Skinke, kogt, skiveskåret",c:109},
{n:"Bækforel, rå",c:98},
{n:"Kødboller, dybfrost",c:163},
{n:"Æg, høne, pasteuriseret",c:131},
{n:"Lever, kalv, rå",c:131},
{n:"Kalvekød, helt magert, råt",c:92},
{n:"Helleflynder, røget",c:104},
{n:"Hvedebrød, toastbrød, fint, industrifremstillet",c:255},
{n:"Grisespæk, rygspæk, råt",c:661},
{n:"Brombær, dybfrost, usukrede",c:45},
{n:"Kokosmel",c:636},
{n:"Brissel, lam, rå",c:131},
{n:"Høne, kød, rå",c:110},
{n:"Ribsgele",c:238},
{n:"Helleflynder, rå",c:104},
{n:"Lever, kylling, rå",c:116},
{n:"Ørred, hav-, rå",c:130},
{n:"Batat, sød kartoffel, rå",c:72},
{n:"Bladbede, sølvbede, rå",c:21},
{n:"Løg, rå",c:43},
{n:"Jordbær, syltede",c:202},
{n:"Sapodille (chiku), rå",c:81},
{n:"Kaffe, instant, pulver",c:302},
{n:"Parmesan, revet",c:428},
{n:"Hvedebrød, bolle, grov, industrifremstillet",c:246},
{n:"Grisekød, skinke af inderlår, helt afpudset, rå",c:106},
{n:"Kirsebær, syltede",c:144},
{n:"Torsk, filet, stegt",c:120},
{n:"And, kød, rå",c:126},
{n:"Kalkun, bryst (filet), kogt/røget, pålæg",c:107},
{n:"Pizza med tunfisk, dybfrost",c:203},
{n:"Flødeskumskage, kartoffelkage",c:374},
{n:"Kalkun, kød, rå",c:105},
{n:"Grisekød, skinkemignon af lårtunge, helt afpudset, rå",c:117},
{n:"Loganbær, frosne",c:50},
{n:"Rugbrød, med sigtet mel (soft) og fedtrige frø, industrifremstillet",c:228},
{n:"Stenbider, rå",c:168},
{n:"And, brystkød, rå",c:116},
{n:"Grisekød, filet, helt afpudset, rå",c:106},
{n:"Forårsløg, rå",c:33},
{n:"Lever, okse, rå",c:122},
{n:"Grisefilet, røget, pålæg",c:112},
{n:"Tørkage, napoleonshatte",c:485},
{n:"Hvedebrød, toastbrød, groft, industrifremstillet",c:256},
{n:"Grisekød, skinke af yderlår, helt afpudset, råt",c:115},
{n:"Lever, ande, rå",c:131},
{n:"Marcipanprodukt, m/chokolade, uspec.",c:526},
{n:"Hamburgerryg, røget",c:121},
{n:"Hamburgerryg, kogt",c:119},
{n:"Tun i tomat, konserves",c:117},
{n:"Savoykål, rå",c:27},
{n:"Asparges, uspec., rå",c:23},
{n:"Kylling, bryst (filet), kogt, pålæg",c:113},
{n:"Citronskal, rå",c:52},
{n:"Pistacienød, tørristet med salt",c:589},
{n:"Kirsebærsaft, sød, koncentreret",c:171},
{n:"Ribssaft, sød, koncentreret",c:171},
{n:"Hindbærsaft, sød, koncentreret",c:171},
{n:"Jordbærsaft, sød, koncentreret",c:171},
{n:"Grønne bønner, rå",c:30},
{n:"Dild, tørret",c:319},
{n:"Pølsebrød",c:253},
{n:"Selleri, blade, rå",c:34},
{n:"Helt, rå",c:113},
{n:"Tyttebær, rå",c:54},
{n:"Oksekød, inderlår uden kappe, rå",c:118},
{n:"Grisekød, mørbrad, afpudset, rå",c:115},
{n:"Knækbrød, hvede-, fint",c:399},
{n:"Harekød, uspec., råt",c:112},
{n:"Ørred, regnbue-, rå",c:153},
{n:"Koriander, frø",c:358},
{n:"Hjerte, høne (kylling), råt",c:149},
{n:"Grisekød, uspec., magert, råt",c:114},
{n:"Torsk, rogn, rå",c:120},
{n:"Lever, gris, rå",c:122},
{n:"Krabbekløer, rå",c:112},
{n:"Krabbekløer, konserves",c:112},
{n:"Kalkun, kød og skind, rå",c:126},
{n:"Grovfranskbrød",c:259},
{n:"Marcipan",c:478},
{n:"Grisekød, bov, helt afpudset, rå",c:126},
{n:"Hvedebrød, kastanjebrød",c:258},
{n:"Hyldebærsaft, sød, koncentreret",c:219},
{n:"Fennikel, frø",c:327},
{n:"Marmelade, engelsk type",c:277},
{n:"Kylling, kød, rå",c:128},
{n:"Lammekød, kølle, afpudset, rå",c:128},
{n:"Hvalkød, råt",c:111},
{n:"Kalvekød, magert, råt",c:121},
{n:"Blomkål, dansk, rå",c:19},
{n:"Krabbe, kogt",c:129},
{n:"Kartoffel, kogt",c:85},
{n:"Rype, kød, rå",c:112},
{n:"Abrikosmarmelade",c:221},
{n:"Chokolade, fløde, med nødder",c:572},
{n:"Oksekød, tykstegsfilet uden kappe, rå",c:123},
{n:"Pinjekerner, tørret",c:678},
{n:"Kaninkød, uspec., råt",c:118},
{n:"Peber, chili, rå",c:44},
{n:"Sælkød, råt",c:114},
{n:"Flûte, groft, industrifremstillet",c:259},
{n:"Cashewnød, tørristet",c:603},
{n:"Hvedebrød, bolle, italiensk type, industrifremstillet",c:256},
{n:"Oksekød, uspec., helt magert, råt",c:125},
{n:"Oksekød, klump uden kappe, rå",c:147},
{n:"Kaviar, uægte (lodderogn)",c:185},
{n:"Morgenmadsprodukt, Guldkorn",c:386},
{n:"Porre, rå",c:35},
{n:"Tun i vand, konserves",c:107},
{n:"Flødeskumskage, walesbolle/-kringle",c:324},
{n:"Roastbeef, pålæg",c:120},
{n:"Flødeskumskage, uspec.",c:312},
{n:"Oksekød, mørbrad, afpudset, rå",c:138},
{n:"Fårekød, kølle, rå",c:134},
{n:"Frugtpålæg, figen",c:316},
{n:"Koriander, blade, tørrede",c:318},
{n:"Hvedebrød, trekornsbrød",c:264},
{n:"Bondebrød med fedtrige frø, industrifremstillet",c:235},
{n:"Hvedebrød, bolle, fin, industrifremstillet",c:270},
{n:"Kartoffel, chips (franske kartofler)",c:532},
{n:"Appelsinmarmelade",c:202},
{n:"Grisekød, bagskank uden svær, rå",c:143},
{n:"Ørred, dam-, sø-, rå",c:145},
{n:"Spinat, hakket, dybfrost",c:26},
{n:"Fasan, kød, rå",c:122},
{n:"Yams, rå",c:111},
{n:"Kartoffel, ny (maj til september), rå",c:76},
{n:"Bøfsandwich med salat og dressing, fastfood",c:227},
{n:"Æg, and, rå",c:181},
{n:"Grisekød, tunge, rå",c:182},
{n:"Kiwimarmelade",c:225},
{n:"Tunge, gris, saltet",c:182},
{n:"Frugtpålæg, uspec.",c:320},
{n:"Due, vildt, kød, rå",c:142},
{n:"Franskbrød",c:271},
{n:"Solbærsaft, sød, koncentreret",c:199},
{n:"Hvedebrød, valnøddebrød",c:280},
{n:"Peanuts, (jordnød, ristet og saltet)",c:632},
{n:"Brisling, rå",c:136},
{n:"Koriander, blade, friske",c:22},
{n:"Bambusskud, konserves, saltet",c:23},
{n:"Bambusskud, konserves, usaltet",c:23},
{n:"Oksekød, skank (osso buco), rå",c:140},
{n:"Oksekød, højrebsfilet, afpudset, rå",c:173},
{n:"Syre (krydderplante), rå",c:23},
{n:"Kvark, 45+",c:197},
{n:"Æg, gås, rå",c:180},
{n:"Sukker, brun farin",c:382},
{n:"Kaffe, instant, decaffeinated, pulver",c:352},
{n:"Asparges, hvide, rå",c:26},
{n:"Oksekød, yderlår, råt",c:146},
{n:"Rosin uden kerner",c:333},
{n:"Solbær, syltede",c:197},
{n:"Kylling, ben, kød og skind, rå",c:152},
{n:"Solbærmarmelade",c:199},
{n:"Kylling, lår, kød og skind, rå",c:155},
{n:"Flûte med fedtrige frø, industrifremstillet",c:270},
{n:"Grønkål, frossent",c:24},
{n:"Kørvel, hakket, dybfrost",c:24},
{n:"Oksekød, lårtunge, rå",c:145},
{n:"Melbanan, plantain, rå",c:131},
{n:"Tyggegummi, med sukker, uspec.",c:358},
{n:"Cherimoya, rå",c:78},
{n:"Hellefisk, gravad",c:178},
{n:"Hellefisk, rå",c:178},
{n:"Knækbrød, fladbrød",c:361},
{n:"Hvedebrød, sandwich/toastbrød med fedtrige frø, industrifremstillet",c:268},
{n:"Wienerpølse, konserves",c:201},
{n:"Kongeål (pighaj), rå",c:161},
{n:"Bolcher, blandede",c:390},
{n:"Tun, rå",c:117},
{n:"Kalkunkød, hakket, 0-5% fedt, råt",c:131},
{n:"Likør, kaffe med fløde",c:332},
{n:"Kylling, bryst, kød og skind, rå",c:149},
{n:"Nougat",c:560},
{n:"Oksekød, uspec., magert, råt",c:152},
{n:"Oksekød, tunge, rå",c:187},
{n:"Tunge, kalv, saltet",c:157},
{n:"Broccoli, kogt",c:35},
{n:"Marmelade, uspec.",c:202},
{n:"Kirsebærmarmelade",c:202},
{n:"Sild, paneret, stegt, i lage",c:272},
{n:"Laks, atlantisk, vild, konserves",c:228},
{n:"Tomatketchup, stærk",c:102},
{n:"Hestekød, råt",c:166},
{n:"Sardin, i tomat, konserves",c:156},
{n:"Kyllingepølse, pålæg",c:194},
{n:"Champignon, konserves",c:22},
{n:"Hvedebrød, solsikkebrød",c:269},
{n:"Purløg, rå",c:26},
{n:"Kumquat, guldorange, dværgappelsin, rå",c:65},
{n:"Kalvekød, Tunge, rå",c:160},
{n:"Grisekød, skinkeculotte af yderlår, ca. 2 mm spæk, rå",c:162},
{n:"Krydderskinke, udbenet",c:203},
{n:"Pastinak, rå",c:63},
{n:"Kartoffel, efterår (oktober til januar), rå",c:86},
{n:"Maniok, kassava, rå",c:157},
{n:"Oksekød, inderlår med kappe, rå",c:162},
{n:"Oksekød, hakket, 10-15% fedt, rå",c:164},
{n:"Tyggegummi, uden sukker, uspec.",c:342},
{n:"Oksekød, mellemskært, råt",c:164},
{n:"Grisekød, hakket, 5-10% fedt, råt",c:168},
{n:"Kartoffel, gammel (februar - juni), rå",c:81},
{n:"Klipfisk, rå",c:99},
{n:"Grisekød, nakkefilet, helt afpudset (Nakkekotelet), rå",c:182},
{n:"Jordskok, rå",c:79},
{n:"Likør, kaffe",c:342},
{n:"Gås, kød, rå",c:158},
{n:"Rundstykke, spansk",c:281},
{n:"Grønkål, konserves",c:30},
{n:"Spinat, konserves",c:22},
{n:"Kylling, kød og skind, rå",c:174},
{n:"Makrel i tomat, konserves",c:154},
{n:"Champignon, rå",c:23},
{n:"Roulade, abrikos",c:327},
{n:"Oksekød, tykstegsfilet med kappe, rå",c:171},
{n:"Kiks, Marie",c:435},
{n:"Karse, frisk",c:27},
{n:"Bønnespirer, mung, rå",c:34},
{n:"Lakrids, sød",c:345},
{n:"Hindbærmarmelade",c:203},
{n:"Grisekød, skinkesteg af yderlår, med svær, rå",c:182},
{n:"Gaffelbidder",c:192},
{n:"Persillerod, rå",c:55},
{n:"Vallepulver, tørret",c:359},
{n:"Bønnespirer, uspec., rå",c:37},
{n:"Minarine, 30 %, vegetabilsk fedt",c:319},
{n:"Oksekød, tykbov (marvpibebov), rå",c:182},
{n:"Torsk, rogn, røget",c:145},
{n:"Medisterpølse, rå",c:219},
{n:"Kalvekød, middelfedt, råt",c:184},
{n:"Grisekød, bov med svær, rå",c:189},
{n:"Smørbart blandingsprodukt, 80% fedt",c:731},
{n:"Skumfiduser, uspec.",c:345},
{n:"Grisekød, uspec., ca. 10 % fedt, råt",c:183},
{n:"Sylte",c:217},
{n:"Kylling, vinge, kød og skind, rå",c:187},
{n:"Hvedebrød med fedtrige frø, store, industrifremstillet",c:267},
{n:"Brisling (sardin), i tomat, konserves",c:206},
{n:"Lammekød, bov, rå",c:231},
{n:"Fasan, kød og skind, rå",c:170},
{n:"Jordbærmarmelade",c:226},
{n:"Laks, atlantisk, vild, koldrøget",c:162},
{n:"Pastiller, sukkerfri, uspec.",c:247},
{n:"Hellefisk, røget",c:202},
{n:"Grisekød, kam uden svær, ca. 3 mm spæk, rå",c:196},
{n:"Blomkål, importeret, rå",c:31},
{n:"Fruktose",c:399},
{n:"Salt, stensalt, køkkensalt",c:0},
{n:"Karameller, blandede",c:482},
{n:"Leverpostej",c:238},
{n:"Æblegele",c:243},
{n:"Solbærgele",c:243},
{n:"Grovbolle",c:286},
{n:"Smør, usaltet",c:743},
{n:"Gåsefedt",c:898},
{n:"Lammekød, kølle, med fedt, rå",c:201},
{n:"Plantemargarine, 80%, stege/bage",c:726},
{n:"Oksekød, tykkam, rå",c:193},
{n:"Margarine, 80 %, bordbrug, blød, vegetabilsk fedt",c:727},
{n:"Skinke, røget, kogt",c:199},
{n:"Chokolade, mørk",c:549},
{n:"Tomatsuppe, spiseklar",c:72},
{n:"Sild, marineret, kryddersild",c:229},
{n:"Kødrand, dybfrost",c:218},
{n:"Sild, røget",c:216},
{n:"Grisekød, skinkeculotte af yderlår, ca. 5 mm spæk, råt",c:222},
{n:"Laks, atlantisk, vild, gravad",c:178},
{n:"Margarine, 80 %, bordbrug, vegetabilsk fedt",c:731},
{n:"Ansjos, marineret, konserves",c:215},
{n:"Brisling (ansjovis), marineret, konserves",c:215},
{n:"Margarine, 80 %, stegning/bagning, animalsk og vegetabilsk fedt",c:737},
{n:"Høne, kød og skind, rå",c:214},
{n:"Margarine, 80 %, bordbrug, animalsk og vegetabilsk fedt",c:739},
{n:"Oksekød, spidsbryst, råt",c:167},
{n:"Poulard, kød og skind, rå",c:190},
{n:"Oksekød, tyndbov + mellembov, rå",c:205},
{n:"Skinkepølse, pålæg",c:222},
{n:"Margarine, gennemsnit",c:742},
{n:"Flødeskumskage, gåsebryst",c:359},
{n:"Hvedebrød, bolle, grov, med fedtrige frø, industrifremstillet",c:280},
{n:"Skummetmælk, økologisk",c:35},
{n:"Skummetmælk",c:35},
{n:"Bambusskud, rå",c:37},
{n:"Smør, saltet",c:741},
{n:"Oksekød, uspec., middelfedt, råt",c:242},
{n:"Sild, marineret, i madeirasauce",c:232},
{n:"Passionsfrugt, rå",c:104},
{n:"Pølse, bierwurst",c:228},
{n:"Syltetøj, uspec.",c:267},
{n:"Grisekød, rullesteg af slag, råt",c:217},
{n:"Roulade, hindbær",c:379},
{n:"Bayonneskinke, udbenet",c:193},
{n:"Sukkerært (mangetout), rå",c:48},
{n:"Roulade, uspec.",c:351},
{n:"Rundstykke",c:294},
{n:"Oksekød, culotte, rå",c:271},
{n:"Lakrids, uspec.",c:359},
{n:"Minimælk, 0.5 % fedt",c:37},
{n:"Oksekød, hakket, 15-20% fedt, rå",c:217},
{n:"Kærnemælk med citronsaft",c:50},
{n:"Oksekød, tyndsteg med mørbrad, rå",c:211},
{n:"Kalv- og svinekød, hakket kalv og flæsk, 15-20% fedt, råt",c:218},
{n:"Flødeskumskage, medalje",c:370},
{n:"Jagtpølse, pålæg",c:237},
{n:"Kaffebønne, ristet, formalet",c:399},
{n:"Grisekød, hakket, 15-20% fedt, råt",c:224},
{n:"Grisekød, kogestykke af bryst uden svær, ca. 2 mm spæk, rå",c:228},
{n:"Sild, marineret, i karrysauce",c:279},
{n:"Kakao, instant, med mælk, pulver",c:382},
{n:"Rødspætte, filet, paneret, friturestegt",c:251},
{n:"Risklid",c:398},
{n:"Oksekød, tyndstegsfilet med fedtkant, rå",c:212},
{n:"Tørkage, kransekage",c:443},
{n:"Hvedekim, rå",c:379},
{n:"Kuller, paneret, stegt",c:198},
{n:"Tun i olie, konserves",c:202},
{n:"Skorzonerrod, rå",c:75},
{n:"Fårekød, bov, rå",c:228},
{n:"Kylling, kød og skind, grillstegt",c:194},
{n:"Chokolade, koge-",c:562},
{n:"Wienerpølse, kogt, fastfood",c:261},
{n:"Flødeskumskage, napoleonskage",c:359},
{n:"Mælkebøtte, blade, rå",c:46},
{n:"Kanel, stang",c:246},
{n:"Sirup",c:308},
{n:"Paté, pålæg",c:257},
{n:"Kantarel, rå",c:27},
{n:"Kødpølse, pålæg",c:272},
{n:"Sapote, stor sapodil, rå",c:144},
{n:"Flæskesvær, snacks",c:580},
{n:"Malakoffpølse, pålæg",c:273},
{n:"Makrel, filet, naturel, konserves",c:224},
{n:"Ribbensstegssandwich",c:277},
{n:"Cacaoskummetmælk",c:58},
{n:"Cacaoskummetmælk (UHT)",c:59},
{n:"Oksekød, højrebsfilet med kappe, rå",c:214},
{n:"Camembert, 30+",c:199},
{n:"Lucernespirer, rå",c:27},
{n:"Grisekød, uspec., ca. 20 % fedt, råt",c:243},
{n:"Lakrids, salt",c:349},
{n:"Kiks, 20-30% fuldkorn, digestivetype",c:460},
{n:"Grisekød, mellemkam med svær, rå",c:268},
{n:"Vingummi",c:349},
{n:"Brisling (sardin), i olie, konserves",c:205},
{n:"Sardin, i olie, konserves",c:205},
{n:"Kiks til ost, Cream Crackers",c:443},
{n:"Grisekød, kogestykke af bryst med svær, rå",c:294},
{n:"Modermælk, colostrum",c:58},
{n:"Morgenmadsprodukt, Havrefras",c:377},
{n:"Pølse, cervelatpølse, pålæg",c:277},
{n:"Mintgele",c:266},
{n:"Sild, høstsild, fedsild, rå",c:248},
{n:"Spædbørnsmad, modermælkserstatning, lavt jernindhold, drikkeklar",c:66},
{n:"Vekao",c:561},
{n:"Medisterpølse, røget",c:279},
{n:"Bacon i skiver, rå",c:263},
{n:"Sandwich med skinke og ost, toasted, fastfood (Parisertoast)",c:298},
{n:"Lucerne, alfalfa, frø",c:351},
{n:"Wienerpølse",c:254},
{n:"Dressing, mayonnaise",c:348},
{n:"Rugsigtemel (udmalingsgrad ca. 70 %)",c:342},
{n:"Oksekød, entrecote med kappe, rå",c:265},
{n:"Kippers i olie, konserves",c:249},
{n:"Spegesild",c:264},
{n:"Letmælkskefir",c:48},
{n:"Letmælk, økologisk",c:47},
{n:"Dressing, olie-eddike",c:350},
{n:"Muskatnød, hel",c:507},
{n:"Rullepølse, pålæg",c:272},
{n:"Rosenkål, vinter (januar til april), rå",c:51},
{n:"Kørvel, rå",c:21},
{n:"Pølse, bratwurst, thüringer",c:283},
{n:"Jordnøddesmør",c:637},
{n:"Pølse, krakowpølse",c:284},
{n:"Majs, kerner, konserves",c:101},
{n:"Æble, tørret",c:253},
{n:"Modermælk, overgangsmælk (10. dag efter fødslen)",c:67},
{n:"Yoghurt, med frugt, 1.5 % fedt",c:72},
{n:"Kalvekød, fedt, råt",c:274},
{n:"Sprængt nakke, grisekød",c:264},
{n:"Småkage, uspec.",c:502},
{n:"Fløde 38 %, piskefløde",c:360},
{n:"Honning",c:327},
{n:"Sojadrik, kommercielt tilberedt, ikke beriget",c:50},
{n:"Modermælk, moden",c:71},
{n:"Creme fraiche 38 %",c:362},
{n:"Laks, atlantisk, vild, saltet",c:198},
{n:"Blodpølse, kogt",c:312},
{n:"Æg, høne, blomme, saltet, pasteuriseret",c:269},
{n:"Bækforel, filet, røget",c:204},
{n:"Cacaomælk (UHT)",c:69},
{n:"Gelatine",c:349},
{n:"Minarine, gennemsnit",c:373},
{n:"Wienerpølse, ristet, fastfood",c:292},
{n:"Pekannød, olieristet",c:747},
{n:"Pecannød, tørristet",c:742},
{n:"Minarine, 40 %, vegetabilsk fedt",c:374},
{n:"Rosenkål, efterår (oktober til december), rå",c:57},
{n:"Boghvedemel",c:343},
{n:"Gær, tørret",c:315},
{n:"Due, vildt, kød og skind, rå",c:287},
{n:"Grisekød, stegestykke af bryst, uden svær, ca. 2 mm spæk, rå",c:303},
{n:"Smelteost, 20+",c:223},
{n:"Danbo, 20+",c:225},
{n:"Tang, kombu, tørret",c:186},
{n:"Cacaomælk",c:69},
{n:"Kakao, instant, uden mælk, pulver",c:392},
{n:"Gærekstrakt, marmite",c:155},
{n:"Pommes frites, friturestegt, fastfood",c:302},
{n:"Æg, blomme, tilsat sukker, pasteuriseret, dybfrost",c:313},
{n:"Ost, fast, 20+, alle typer",c:224},
{n:"Flødeost, 60+",c:334},
{n:"Tomatpure, koncentreret",c:89},
{n:"Sojabønner, tørrede, rå",c:412},
{n:"Kødekstrakt, terning",c:238},
{n:"Makrel, røget",c:300},
{n:"Kogt oksebryst, pålæg",c:275},
{n:"Kammerjunkere",c:467},
{n:"Risengryn, grødris, polerede, rå",c:360},
{n:"Skinke, røget",c:231},
{n:"Smelteost, 30+",c:256},
{n:"Brie, 45+",c:285},
{n:"Kylling, kød og skind, paneret, friturestegt",c:282},
{n:"Æg, høne, blomme, rå",c:324},
{n:"Oksekød, uspec., fedt, råt",c:322},
{n:"Oksekød, tyndbryst, råt",c:278},
{n:"Lammekød, uspec., råt",c:330},
{n:"Camembert, 45+",c:288},
{n:"Kylling, kød og skind, friturestegt",c:260},
{n:"Oksekød, tykbryst, råt",c:229},
{n:"Sildepostej",c:346},
{n:"Boghvedegryn, rå",c:355},
{n:"Feta, 50+",c:303},
{n:"Skummetmælksost, max. 5+",c:185},
{n:"Tomatpure",c:43},
{n:"Ål, rå",c:310},
{n:"Grisekød, stegestykke af bryst med svær, rå",c:358},
{n:"Oksekød, tværreb, råt",c:330},
{n:"Ris, polerede, rå",c:354},
{n:"Bouillon, oksekød, koncentreret, terning",c:160},
{n:"Rismel",c:360},
{n:"Kakao, pulver",c:405},
{n:"Oliven, sorte, saltede, i olie",c:358},
{n:"Rugmel, halvsigtet (udmalingsgrad ca. 85 %)",c:339},
{n:"Danbo, 30+",c:257},
{n:"Oksekød, slag, råt",c:335},
{n:"Tomatketchup",c:114},
{n:"Sødmælk (UHT)",c:63},
{n:"Sødmælk, økologisk",c:64},
{n:"Lammekød, rygstykke, råt",c:290},
{n:"Grisekød, uspec., fedt, råt",c:346},
{n:"Yoghurt med jordbær",c:84},
{n:"Ris, parboiled, rå",c:358},
{n:"Kartoffelmel",c:342},
{n:"Yoghurt med skovbær",c:86},
{n:"Ost, fast, 30+, alle typer",c:263},
{n:"Spædbørnsmad, modermælkserstatning, højt jernindhold, pulver",c:505},
{n:"Fersken, tørret",c:333},
{n:"Camembert, 50+",c:305},
{n:"Yoghurt med peach melba",c:87},
{n:"Yoghurt, sødmælk, med frugt",c:89},
{n:"Maribo, 30+",c:268},
{n:"Yoghurt med pære og banan",c:89},
{n:"Yoghurt med kirsebær",c:89},
{n:"A38, acidophilus tykmælk af sødmælk, 3,5% fedt",c:65},
{n:"Birkes, frø",c:539},
{n:"Bygmel",c:338},
{n:"Pastiller, med sukker, uspec.",c:349},
{n:"Pasta, kogt",c:128},
{n:"Majsmel",c:361},
{n:"Mozzarella, 30+",c:279},
{n:"Hvedemel",c:343},
{n:"Ål, røget",c:329},
{n:"Flødeost, 70+",c:380},
{n:"Yoghurt med müsli",c:87},
{n:"Hvedemel, bagerimel",c:349},
{n:"Hvedegryn, mannagryn",c:353},
{n:"Bagepulver",c:172},
{n:"Brie, 50+",c:331},
{n:"Grønne ærter, konserves",c:75},
{n:"Lammekød, slag, råt",c:369},
{n:"Lammekød, bryst, råt",c:369},
{n:"Bønnespirer, soja, rå",c:57},
{n:"Samsø, 30+",c:279},
{n:"Gedemælk",c:69},
{n:"Tidselolie",c:900},
{n:"Majskimolie",c:900},
{n:"Theboller o.l. (bløddejsboller)",c:296},
{n:"Hvedekimolie",c:900},
{n:"Bomuldsfrøolie",c:900},
{n:"Sorbitol",c:240},
{n:"Palmeolie",c:900},
{n:"Kakaosmør",c:900},
{n:"Sennep, pulver",c:482},
{n:"Palmekerneolie",c:900},
{n:"Jordnøddeolie",c:900},
{n:"Solsikkeolie",c:900},
{n:"Valnøddeolie",c:900},
{n:"Rødbede, dansk, rå",c:41},
{n:"Grønkål, dansk, rå",c:43},
{n:"Salat, Iceberg, dansk, rå",c:12},
{n:"Torsk, levertran",c:900},
{n:"Melboller, dybfrost",c:211},
{n:"Sesamolie",c:900},
{n:"Salat, Iceberg, importeret, rå",c:14},
{n:"Sukker, brunt rørsukker",c:399},
{n:"Majsolie",c:900},
{n:"Hørfrøolie",c:900},
{n:"Rugbrød, soft, uden fedtrige frø, uden kerner, industrifremstillet",c:210},
{n:"Hvedebrød, italiensk type, stort, detailbageri",c:249},
{n:"Vindruekerneolie",c:900},
{n:"Kokosolie",c:899},
{n:"Levertran (Sej)",c:900},
{n:"Oksetalg",c:875},
{n:"Sojaolie",c:900},
{n:"Fiskefilet, paneret, friturestegt, fastfood",c:286},
{n:"Olivenolie",c:900},
{n:"Rapsolie",c:900},
{n:"Selleri, rod, dansk, rå",c:30},
{n:"Rucola, rå",c:21},
{n:"Græskarkerner, tørret",c:568},
{n:"Hvedemel, durum",c:347},
{n:"Hvedebrød, fint, store, industrifremstillet",c:262},
{n:"Hvedebrød, fint, store, detailbageri",c:274},
{n:"Hvedebrød, groft, store, industrifremstillet",c:253},
{n:"Hvedebrød, groft, store, detailbageri",c:256},
{n:"Tigerreje, opdræt, rå, dybfrost",c:68},
{n:"Reje, sort tiger-, opdræt, kogt, dybfrost",c:58},
{n:"Laks, atlantisk, opdræt, koldrøget",c:170},
{n:"Laks, atlantisk, opdræt, varmrøget",c:267},
{n:"Hvid hvede, melmix",c:341},
{n:"Småkage, hvede, traditionelle danske, industrifremstillet",c:520},
{n:"Småkage, cookie (amerikansk type), industrifremstillet",c:511},
{n:"Småkage, havreflager, industrifremstillet",c:504},
{n:"Småkage, brunkage, industrifremstillet",c:469},
{n:"Småkage, pebernød, industrifremstillet",c:476},
{n:"Småkage, klejne, industrifremstillet",c:527},
{n:"Småkage, med lavt sukkerindhold (sukkerfri, light) industrifremstillet",c:483},
{n:"Småkage, kokoskager, industrifremstillet",c:460},
{n:"Kage, trøffelprodukt / koldprodukt, industrifremstillet",c:449},
{n:"Kransekage, industrifremstillet",c:443},
{n:"Babymajs, rå",c:37},
{n:"Pomelo, rå",c:57},
{n:"Kiks, rug",c:446},
{n:"Kiks, hvede, sød, med tyk chokolade",c:504},
{n:"Kiks, dobbelte, hvede, søde",c:481},
{n:"Kiks, havre, søde",c:468},
{n:"Kiks, havre, søde, med chokolade",c:489},
{n:"Müslibar",c:435},
{n:"Vaffelrør",c:510},
{n:"Kiks, grov med frugt eller grønt",c:433},
{n:"Skummetmælk, 0.1 % fedt",c:35},
{n:"Yoghurt naturel, 1.5 % fedt",c:48},
{n:"Yoghurt naturel, 0.1 % fedt",c:39},
{n:"Hvid hvede brød, groft, store, detailbageri",c:252},
{n:"Hvid hvede bolle, grov, industrifremstillet",c:231},
{n:"Hvid hvede brød, groft, store, industrifremstillet",c:223},
{n:"Sild, Østersø, uspecificeret, rå",c:123},
{n:"Oksekød, hakket, 5-10% fedt, rå",c:163},
{n:"Grisekød, hakket, 10-15% fedt, råt",c:169},
{n:"Kalkunkød, hakket, 5-10% fedt, råt",c:157},
{n:"Burger med lille bøf, salat og dressing, fastfood",c:226},
{n:"Burger med medium bøf, salat og dressing, fastfood",c:225},
{n:"Burger med stor bøf, salat og dressing, fastfood",c:231},
{n:"Burger med bøf og bacon, salat og dressing, fastfood",c:255},
{n:"Burger med bøf og ost, salat og dressing, fastfood",c:236},
{n:"Burger med bøf, bacon og ost, salat og dressing, fastfood",c:239},
{n:"Burger med kylling, salat og dressing, fastfood",c:226},
{n:"Sandwich med kylling, salat og dressing, fastfood",c:220},
{n:"Sandwich med kylling og bacon, salat og dressing, fastfood",c:202},
{n:"Sandwich med skinke og ost, salat og dressing, fastfood",c:225},
{n:"Sandwich med æg / rejer, salat og dressing, fastfood",c:186},
{n:"Sandwich med fisk, salat og dressing, fastfood",c:203},
{n:"Sandwich med kebab, salat og dressing, fastfood",c:216},
{n:"Sandwich med ribbenssteg, rødkål og agurk, fastfood",c:251},
{n:"Trekantsandwich med kylling og bacon, salat og dressing, fastfood",c:206},
{n:"Trekantsandwich med skinke og ost, salat og dressing, fastfood",c:229},
{n:"Trekantsandwich med æg, salat og dressing, fastfood",c:204},
{n:"Sandwich med frikadelle, salat og dressing, fastfood",c:219},
{n:"Pitasandwich med kebab, salat og dressing, fastfood",c:206},
{n:"Pitasandwich med kylling, salat og dressing, fastfood",c:165},
{n:"Pitasandwich med rejer, salat og dressing, fastfood",c:128},
{n:"Pitasandwich med falafel, salat og dressing, fastfood",c:231},
{n:"Pitasandwich med salat og dressing, fastfood",c:150},
{n:"Dürumrulle med kebab, salat og dressing, fastfood",c:217},
{n:"Pølse med bacon, ristet, fastfood",c:318},
{n:"Fransk hot dog, fastfood",c:288},
{n:"Hot dog, almindelig, fastfood",c:256},
{n:"Pølsemix med pommes frites, fastfood",c:323},
{n:"Kebabmix med pommes frites, friturestegt, fastfood",c:294},
{n:"Kylling, grillstegt, fastfood",c:196},
{n:"Kyllingenuggets, friturestegt, fastfood",c:280},
{n:"Pizza med tomat og ost, fastfood",c:319},
{n:"Pizza med fisk, tomat og ost, fastfood",c:256},
{n:"Pizza med salami, tomat og ost, fastfood",c:316},
{n:"Pizza med grønt og frugt, tomat og ost, fastfood",c:220},
{n:"Pizza med kød, tomat og ost, fastfood",c:257},
{n:"Pizza med kød og fisk, tomat og ost, fastfood",c:228},
{n:"Fiskefilet, paneret, stegt, delikatesse",c:281},
{n:"Tun, gulfinnet, rå",c:113},
{n:"Reje, dybvands, kogt, i lage",c:71},
{n:"Laks, atlantisk, opdræt, gravad",c:170},
{n:"Skrubbe, filet, paneret, rå, dybfrost",c:150},
{n:"Fiskepinde, panerede, dybfrost",c:185},
{n:"Laks, atlantisk, opdræt, rå",c:228},
{n:"Laks, Stillehavs-, vild, rå",c:105},
{n:"Hajmalle, rå, dybfrost",c:69},
{n:"Blåmusling, kogt",c:112},
{n:"Æg, høne, burhøns, rå",c:137},
{n:"Æg, høne, frilands høns, rå",c:137},
{n:"Æg, høne, skrabehøns, rå",c:138},
{n:"Æg, høne, økologisk drift, rå",c:139},
{n:"Æg, høne, kogt, dybfrost",c:146},
{n:"Æg, høne, blomme, pasteuriseret",c:245},
{n:"Æg, høne, røræg, industrifremstillet",c:118},
{n:"Æg, høne, røræg mix, industrifremstillet",c:132},
{n:"Rugbrød, mørkt, industrifremstillet",c:198},
{n:"Rugbrød, fuldkorn, industrifremstillet",c:199},
{n:"Hvedebrød, groft, med fedtrige frø, stort, detailbageri",c:281},
{n:"Rugbrød, kun groft rugmel, detailbageri",c:216},
{n:"Rugbrød, kun groft rugmel, med hele kerner, detailbageri",c:210},
{n:"Rugbrød, kun groft rugmel, med fedtrige frø, detailbageri",c:242},
{n:"Rugbrød, med sigtet mel (soft) og fedtrige frø, detailbageri",c:253},
{n:"Yoghurt, med frugt, 0.1 % fedt, uden tilsat sukker",c:43},
{n:"Hytteost, 10+",c:86},
{n:"Hytteost, 5+",c:76},
{n:"Lactose, pulver",c:392},
{n:"Yoghurt med frugt, 0.4 % fedt",c:76},
{n:"Koldskål",c:72},
{n:"Milkshake",c:86},
{n:"Smørbart blandingsprodukt, 75% fedt",c:686},
{n:"Smørbart blandingsprodukt, let, 57% fedt",c:542},
{n:"Grisekød, skinkeklump, helt afpudset, rå",c:100},
{n:"Grisekød, bryst med svær, rå",c:299},
{n:"Grisekød, filet, 0-1 mm fedtkant, rå",c:130},
{n:"Grisekød, kæbe, afpudset, rå",c:117},
{n:"Havredrik, ikke beriget",c:48},
{n:"Risdrik, ikke beriget",c:50},
{n:"Mandeldrik, ikke beriget",c:48},
{n:"Skyr, 0.2 % fedt",c:70},
{n:"Galia melon, rå",c:34},
{n:"Flødeskumskage, chokoladebolle",c:363},
{n:"Kommen, rå",c:334},
{n:"Spidskommen, rå",c:428},
{n:"Tahin, lys",c:641},
{n:"Risdrik, tilsat calcium",c:54},
{n:"Havredrik, tilsat calcium",c:39},
{n:"Sojadrik, tilsat calcium",c:45},
{n:"Hvedebrød, bolle, italiensk type, detailbageri",c:257},
{n:"Hvedebrød, pitabrød, fint",c:251},
{n:"Hvedebrød, pitabrød, groft",c:250},
{n:"Morgenmadsprodukt, med klid",c:327},
{n:"Havtorn, rå",c:75},
{n:"Kalvekød, culotte, rå",c:143},
{n:"Peberfrugt, gul, rå",c:29},
{n:"Speltmel, sigtet",c:348},
{n:"Speltmel, fuldkorn",c:332},
{n:"Quinoa, hvid, rå",c:362},
{n:"Quinoa, rød, rå",c:358},
{n:"Quinoa, sort, rå",c:347},
{n:"Rugmel, uspec.",c:322},
{n:"Chiafrø",c:462},
{n:"Perlespelt",c:329},
{n:"Perlebyg",c:335},
{n:"Flydende olie margarine",c:734},
{n:"Flydende olie margarine, beriget med A- og D-vitamin",c:728},
{n:"Plantemargarine, 80%, stege/bage, beriget med A- og D-vitamin",c:726},
{n:"Plantemargarine, 80%, stege/bage, beriget med A-vitamin",c:726},
{n:"Plantemargarine, 75%, stege/bage, beriget med A-vitamin",c:684},
{n:"Plantemargarine, 60%, bordbrug, blød, beriget med A-vitamin",c:550},
{n:"Minarine, 40%, bordbrug, blød, beriget med A- og D-vitamin",c:365},
{n:"Oksekød, hakket, 8-12% fedt, rå",c:173},
{n:"Kyllingekød, hakket, 3-10% fedt, rå",c:137},
{n:"Babyspinat, rå",c:16},
{n:"Salat, hjerte, rå",c:14},
{n:"Græskar, hokkaido, dansk, rå",c:34},
{n:"Græskar, butternut squash, rå",c:32},
{n:"Valle protein pulver",c:385},
{n:"Riskiks/riskage, poppede brune ris",c:376},
{n:"Spinat, helbladet, dybfrost",c:19},
{n:"Rødkål, dansk, rå",c:24},
{n:"Spidskål, dansk, rå",c:21},
{n:"Pastinak, dansk, rå",c:72},
{n:"Kalvekød, cuvette, rå",c:176},
{n:"Kalvekød, Wienerschnitzel af inderlår, afpudset, rå",c:107},
{n:"Kalvekød, tykstegsfilet, rå",c:104},
{n:"Kalvekød, tyndstegsfilet, rå",c:159},
{n:"Oksekød, cuvette, rå",c:223},
{n:"Oksekød, flanksteak, rå",c:142},
{n:"Gulerødder, importeret, uden skræl, rå",c:36},
{n:"Gulerødder, dansk, uden skræl, rå",c:30},
{n:"Pastinak, importeret, rå",c:66},
{n:"Selleri, rod, importeret, rå",c:20},
{n:"Flødeyoghurt naturel, 10% fedt (Græsk og Tyrkisk stil)",c:121},
{n:"Flødeyoghurt naturel, 2% fedt (Græsk og Tyrkisk stil)",c:71},
{n:"A38, acidophilus tykmælk af letmælk, 1,5% fedt",c:44},
{n:"A38, acidophilus tykmælk af minimælk, 0,5% fedt",c:42},
{n:"Pizza topping (Revet ost, Mozzarella)",c:315},
{n:"Skinkeost 30+ (Smelteost med skinke)",c:216},
{n:"Rejeost, let, 8% fedt, (Smelteost med rejer)",c:151},
{n:"Feta, 5% (Salat-tern)",c:176},
{n:"Flødeost, 30-40+",c:152},
{n:"Flødeost, 45-55+",c:260},
{n:"Brie, 11%",c:176},
{n:"Gedeost, blød, 45-55+",c:311},
{n:"Gedeost, i saltlage, 20-25%",c:271},
{n:"Gedeost, fast, 45+",c:369},
{n:"Skæreost, 6%/10+",c:175},
{n:"Ost, fast, 45+, Dansk",c:325},
{n:"Ost, fast, 50+, Dansk",c:367},
{n:"Kalvekød, bryst, rå",c:147},
{n:"Oksekød, bryst, rå",c:197},
{n:"Pålæg i skiver, med hvedeprotein",c:223},
{n:"Seitan",c:195},
{n:"Hakket, med mycoprotein",c:97},
{n:"Hakket, med sojaprotein",c:169},
{n:"Hakket bolle, med sojaprotein",c:157},
{n:"Stykker, med sojaprotein",c:121},
{n:"Pålæg i skiver, med soja- og ærteprotein",c:153},
{n:"Hakket, med ærteprotein",c:219},
{n:"Pølse, med ærteprotein",c:202},
{n:"Pålæg i skiver, med æggehvide",c:173},
{n:"Stykker, med mycoprotein",c:88},
{n:"Pølse, med sojaprotein",c:164},
{n:"Oksekød, filet, marmoreret, rå",c:190},
{n:"Surbær (Aroniabær)",c:50},
{n:"Havredrik, tilsat calcium og vitaminer",c:62},
{n:"Mandeldrik, tilsat calcium",c:28},
{n:"Linser, røde, tørrede, rå",c:323},
{n:"Linser, grønne, tørrede, rå",c:310},
{n:"Bønner, hvide, tørrede, rå",c:276},
{n:"Bønner, røde kidney, tørrede, rå",c:279},
{n:"Kikærter, tørrede, rå",c:337},
{n:"Le Puy linser (delikatesse linser), tørrede, rå",c:302},
{n:"Linser, beluga, tørrede, rå",c:309},
{n:"Edamamebønner (Sojabønner), pillede, frosne",c:132},
{n:"Linser, grønne, kogte, konserves",c:90},
{n:"Baked beans (hvide bønner i tomatsauce)",c:81},
{n:"Chilibønner (røde kidneybønner i chilisauce)",c:87},
{n:"Bønner, røde kidney, kogte, konserves",c:95},
{n:"Bønner, røde kidney, kogte, spiseklare",c:125},
{n:"Kikærter, lyse, kogte, konserves",c:113},
{n:"Kikærter, lyse, dampede, spiseklare",c:150},
{n:"Bønner, sorte, kogte, konserves",c:107},
{n:"Hvide bønner, tørrede og kogt",c:134},
{n:"Bønner, røde kidney, tørret og kogt",c:131},
{n:"Blåbær, dybfrost",c:48},
{n:"Hindbær, dybfrost",c:48},
{n:"Jordbær, dybfrost",c:29},
{n:"Majs, dybfrost",c:81},
{n:"Ærter, grønne, dybfrost",c:69},
{n:"Grønne bønner (haricots verts), dybfrost",c:31},
{n:"Blomkål, dybfrost",c:12},
{n:"Broccoli, dybfrost",c:19},
{n:"Rosenkål, dybfrost",c:37},
{n:"Supperurter, dybfrost",c:25},
{n:"Rodfrugter, dybfrost",c:26},
{n:"Mango, dybfrost",c:55},
{n:"Granatæblekerner, dybfrost",c:67},
{n:"Ananas, dybfrost",c:52},
{n:"Bærmix, dybfrost",c:53},
{n:"Baby gulerødder, dybfrost",c:23},
{n:"Porrer, dybfrost",c:26},
{n:"Avocado, dybfrost",c:138},
{n:"Wokmix, økologisk, dybfrost",c:29},
{n:"Wokmix, dybfrost",c:26},
{n:"Perleløg, dybfrost",c:32},
{n:"Bønnemix, dybfrost",c:78},
{n:"Rodfrugtfritter, dybfrost",c:137},
{n:"Søde kartoffel fritter, dybfrost",c:165},
{n:"Kartoffelbåde, dybfrost",c:115},
{n:"Halve kartofler, dybfrost",c:95},
{n:"Kartoffel spiraler (Curly fries), dybfrost",c:175},
{n:"Kartoffel røsti, dybfrost",c:162},
{n:"Kartoffel kroketter, dybfrost",c:162},
{n:"Steak fries (tykke pommes frites med skræl), dybfrost",c:119},
{n:"Pommes frites, bølgeskårne, dybfrost",c:129},
{n:"Blåbær, rå",c:54},
{n:"Brombær, rå",c:35},
{n:"Hindbær, rå",c:41},
{n:"Abrikos, rå",c:37},
{n:"Blomme, rå",c:46},
{n:"Fersken, rå",c:42},
{n:"Kirsebær, rå",c:61},
{n:"Ananas, rå",c:46},
{n:"Grapefrugt, rå",c:40},
{n:"Honningmelon, rå",c:34},
{n:"Kiwi, rå",c:52},
{n:"Mango, rå",c:52},
{n:"Vand, postevand",c:0},
{n:"Lollandske rosiner (beige-brun ært), tørret",c:353},
{n:"Ananasjuice",c:49},
{n:"Appelsinjuice",c:43},
{n:"Grapefrugtjuice",c:42},
{n:"Sveskejuice",c:60},
{n:"Æblejuice",c:44},
{n:"Blandet frugtjuice",c:46},
{n:"Gulerodsjuice",c:31},
{n:"Tomatjuice",c:20},
{n:"Blandet grøntsagsjuice",c:24},
{n:"Blandet frugt- og grøntsagsjuice",c:43},
{n:"Frugt smoothie",c:54},
{n:"Frugt- og grøntsag smoothie",c:56},
{n:"Koncentreret blandet frugt- og bærsaft, tilsat sukker, fortyndes 1+4",c:174},
{n:"Koncentreret blandet frugt- og bærsaft, tilsat sukker, fortyndes 1+5",c:181},
{n:"Koncentreret tranebærsaft, tilsat kunstig sødestof, fortyndes 1+4",c:30},
{n:"Koncentreret blandet frugt- og bærsaft, tilsat kunstig sødestof, fortyndes 1+4",c:48},
{n:"Koncentreret blandet frugt- og bærsaft, tilsat sukker og kunstig sødestof, fortyndes 1+4",c:56},
{n:"Frugtnektar, tilsat sukker",c:52},
{n:"Frugtnektar, tilsat kunstig sødestof",c:24},
{n:"Pærecider, tilsat sukker, alkohol<0,7%",c:43},
{n:"Æblecider, tilsat sukker, alkohol<0,7%",c:41},
{n:"Pærecider, tilsat kunstig sødestof, alkohol<0,7%",c:10},
{n:"Fersken iste, tilsat sukker",c:31},
{n:"Citron iste, tilsat sukker",c:31},
{n:"Fersken iste, tilsat kunstig sødestof",c:4},
{n:"Fersken iste, tilsat sukker og kunstig sødestof",c:19},
{n:"Citron iste, tilsat sukker, pulver",c:390},
{n:"Sodavand, tilsat sukker",c:41},
{n:"Sodavand, tilsat kunstig sødestof",c:1},
{n:"Sodavand, tilsat sukker og kunstig sødestof",c:5},
{n:"Læskedrik, tilsat sukker, drikkeklar",c:44},
{n:"Koncentreret læskedrik, tilsat sukker, fortyndes 1+3",c:173},
{n:"Koncentreret læskedrik, tilsat sukker, fortyndes 1+4",c:169},
{n:"Koncentreret læskedrik, tilsat sukker, fortyndes 1+5",c:182},
{n:"Koncentreret læskedrik, tilsat sukker, fortyndes 1+7",c:245},
{n:"Koncentreret læskedrik, tilsat sukker, fortyndes 1+9",c:264},
{n:"Koncentreret læskedrik, tilsat kunstig sødestof, fortyndes 1+4",c:18},
{n:"Koncentreret læskedrik, tilsat kunstig sødestof, fortyndes 1+5",c:19},
{n:"Koncentreret læskedrik, tilsat kunstig sødestof, fortyndes 1+9",c:12},
{n:"Koncentreret læskedrik, tilsat kunstig sødestof, fortyndes 1+11",c:13},
{n:"Koncentreret læskedrik, tilsat sukker og kunstig sødestof, fortyndes 1+7",c:103},
{n:"Koncentreret læskedrik, tilsat sukker og kunstig sødestof, fortyndes 1+11",c:27},
{n:"Pilsner, almindelig, 4-5 % vol.",c:36},
{n:"Pilsner, Classic (Wienerøl), 4-5 % alk. vol.",c:37},
{n:"Pilsner, Guldøl, 5-6 % alk. vol.",c:44},
{n:"Lagerøl, stærk, 7-8 % alk. vol.",c:55},
{n:"Pilsner, let, 2-3 % alk. vol.",c:25},
{n:"Pilsner, alkoholfri",c:17},
{n:"Mørk hvidtøl, 1-2 % alk. vol.",c:47},
{n:"Ale, Mørk, 5-7 % alk. vol.",c:53},
{n:"Ale, Lys (blonde), 6-7 % alk. vol.",c:52},
{n:"Hvedeøl, lys, tysk weissbier stil, 4-6 % alk. vol.",c:43},
{n:"Hvedeøl, belgisk witbier stil, 5-6 % alk. vol.",c:44},
{n:"Porter/Stout, 8 % alk. vol.",c:68},
{n:"Julebryg, 5-6% alk. vol.",c:45},
{n:"Tørret skinke, Serrano",c:265},
{n:"Tørret skinke, Schwarzwalder",c:238},
{n:"Grisekød, kam uden svær, krogmodnet",c:244},
{n:"Chokoladeis af mælk/fløde",c:207},
{n:"Chokoladeis, sukkerfri",c:92},
{n:"Chokolade is, vegansk",c:183},
{n:"Jordbæris af mælk/fløde",c:186},
{n:"Karamelis af mælk/fløde",c:194},
{n:"Nougatis af mælk/fløde",c:203},
{n:"Sorbetis, hindbær",c:116},
{n:"Stracciatella is af mælk/fløde",c:206},
{n:"Vanilje is, <50% fløde",c:190},
{n:"Vanilje is, >50% fløde",c:209},
{n:"Vanilje is, uden fløde",c:180},
{n:"Vanilje is, vegansk",c:149},
{n:"Pindeis, Limonade",c:81},
{n:"Pindeis, Limonade m. overtræk",c:99},
{n:"Pindeis, vanilje m. choko overtræk",c:286},
{n:"Pindeis, vanilje m. choko overtræk og mandler",c:327},
{n:"Pindeis, vanilje m. limonade overtræk",c:126},
{n:"Pindeis, Vanilje m. solbær og choko overtræk",c:285},
{n:"Isbåd, vaffel vaniljeis med jordbærsauce og choko overtræk",c:251},
{n:"Vaffelis, vanilje med choko overtræk og nødder",c:287},
{n:"Hønsesalat, light",c:155},
{n:"Hønsesalat",c:224},
{n:"Skinkesalat, light",c:215},
{n:"Skinkesalat",c:286},
{n:"Tunsalat",c:221},
{n:"Italiensk salat",c:206},
{n:"Æggesalat",c:242},
{n:"Kylling & bacon salat",c:284},
{n:"Peberrodssalat",c:273},
{n:"Karrysalat",c:225},
{n:"Skaldyrssalat",c:383},
{n:"Salatdressing, Thousand Island",c:269},
{n:"Salatdressing, creme fraiche",c:266},
{n:"Salatdressing, hvidløg",c:252},
{n:"Fastfood dressing, burger",c:309},
{n:"Pesto, peberfrugt",c:320},
{n:"Aioli",c:614},
{n:"Pesto, basilikum",c:405},
{n:"Pesto, tomat (Rød pesto)",c:372},
{n:"Salatdressing, Cæsar",c:296},
{n:"Salatdressing, Italiensk",c:103},
{n:"Salatdressing, Honning/Sennep",c:423},
{n:"Mayonnaise",c:715},
{n:"Mayonnaise, fedtreduceret",c:307},
{n:"Mayonnaise, chili",c:442},
{n:"Mayonnaise, vegansk",c:595},
{n:"Remoulade",c:299},
{n:"Remoulade, fedtreduceret",c:226},
{n:"Pizza med skinke og ananas, fastfood",c:257},
{n:"Pizza med kebab, salat og dressing, fastfood",c:253},
{n:"Forårsrulle med grøntsager, friturestegt, fastfood",c:264},
{n:"Ris, kogte",c:171},
{n:"Shawarma kebabkød, takeaway",c:271},
{n:"Sushi, takeaway",c:179},
{n:"Wakame tangsalat med sesamfrø, takeaway",c:82},
{n:"Butter chicken, takeaway",c:191},
{n:"Salat med kylling, takeaway",c:86},
{n:"Pad Thai med rejer, takeaway",c:168},
{n:"Kylling i rød karry, takeaway",c:136},
{n:"Wokret med oksekød, takeaway",c:124},
{n:"Energidrik, tilsat sukker",c:40},
{n:"Energidrik, sukkerfri",c:3},
{n:"Energidrik, tilsat sukker og kunstig sødestof",c:24}
];

